/* eslint-disable */
// @ts-nocheck
// biome-ignore lint: disable
// oxlint-disable
// ------
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399

export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    ChartPanel: typeof import('./src/components/ChartPanel.vue')['default']
    ChatInput: typeof import('./src/components/ChatInput.vue')['default']
    ChatMessage: typeof import('./src/components/ChatMessage.vue')['default']
    ElSwitch: typeof import('element-plus/es')['ElSwitch']
    KgMiniGraph: typeof import('./src/components/KgMiniGraph.vue')['default']
    MapFunctionRail: typeof import('./src/components/map/MapFunctionRail.vue')['default']
    ProspectivityPanel: typeof import('./src/components/map/ProspectivityPanel.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    SourceCard: typeof import('./src/components/SourceCard.vue')['default']
    StatCard: typeof import('./src/components/StatCard.vue')['default']
  }
}
